### ISSUE TITLE
Issue when swap and join

### ISSUE THREAD

**Issue by johngrantuk** [balancer/scaffold-balancer-v3#86]
Using hosted version of scaffold. Sepolia. V3. Tried a couple of pools.
Error is thrown at sign step. (I'm not rejecting the request)
Using Rabby wallet.

```
file: useTransactor.ts ~ error TransactionExecutionError: User rejected the request.

Request Arguments:
  from:   0xdf330Ccb1d8fE97D176850BC127D0101cBe4e932
  to:     0xB12FcB422aAe6720f882E22C340964a7723f2387
  value:  0 ETH
  data:   0x19c6989f00000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000000e000000000000000000000000000000000000000000000000000000000000001e00000000000000000000000000000000000000000000000000000000000000260000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000060000000000000000000000000b12fcb422aae6720f882e22c340964a7723f2387ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff00000000000000000000000000000000000000000000000000000000000000010000000000000000000000007b79995e5f793a07bc00c21412e50ecae098e7f900000000000000000000000000000000000000000000000000005af3107a40000000000000000000000000000000000000000000000000000000ffffffffffff0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004168fe230f76ea3b4e35dc9f6310078e825ae17dbfc102b5b7930131591f7ca9543a9a5ccc0a2a8b3270d4402e6c80a02f44c57644a4a4e8615e15efe55204f26b1b00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000124750283bc0000000000000000000000008fc07bcf9b88ace84c7523248dc4a85f638c95360000000000000000000000007b79995e5f793a07bc00c21412e50ecae098e7f9000000000000000000000000b19382073c7a0addbb56ac6af1808fa49e377b7500000000000000000000000000000000000000000000000000005af3107a400000000000000000000000000000000000000000000000000001587a361616d0eb0000000000000000000000000000000000000000000000000de0b6b3a763ffff00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000

Details: User rejected the request.
Version: viem@1.19.9
    at 1053-0877625b052c8b0e.js:86:150304
    at v (1053-0877625b052c8b0e.js:86:150334)
    at async 3074-8ea313a1ea480dac.js:1:139511
    at async p (page-ce5f949355e7fd15.js:1:15047)Caused by: UserRejectedRequestError: User rejected the request.

Details: User rejected the request.
Version: viem@1.19.9
    at delay.count (1053-0877625b052c8b0e.js:102:27844)
    at async s (1053-0877625b052c8b0e.js:102:51057)
```

**Comment by MattPereira** [comment]
Just confirmed this now is working at https://scaffold.balancer.fi/pools?address=0x4D5cEAdaaA29c8e175feC59257A86B2640380E24&network=11155111

![image](https://github.com/user-attachments/assets/1ee67e54-8c33-4b8d-a968-5349bd4f2cff)
